### ISSUE TITLE
[Enhancement]: Non-interactive mode

### ISSUE THREAD

**Issue by MatthewL246** [PretendoNetwork/SSSL#3]
### Checked Existing

- [X] I have checked the repository for duplicate issues.

### What enhancement would you like to see?

Minor enhancement. Add a way to specify options using environment variables/dotenv, which would switch from interactive prompts to a non-interactive mode.

### Any other details to share? (OPTIONAL)

I can work on this as well. I will also take the opportunity to write a very simple Dockerfile for this project while I'm at it.

**Comment by jonbarrow** [comment]
Sounds good to me. This should be changed to be the default, and a new flag added to enable "interactive mode"

**Comment by MatthewL246** [comment]
By flag, do you mean an argument like `patch.js --interactive` or an environment variable like `SSSL_INTERACTIVE=1`?

**Comment by jonbarrow** [comment]
`--interactive`

**Comment by MatthewL246** [comment]
Why does the current code require converting the certificate from DER to PEM? It seems like it would be easier to do that in the Node.js code and allow the user to just provide the dumped DER.
